routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check()) {
        $user = Auth::user();
        if ($user->status == 'suspended') {
            Auth::logout();
            return redirect()->route('index')->with([
                'flash_status' => 'error',
                'flash_message' => 'Your Account has been suspended.Please Contact Support.'
            ]);
        } else {

            if ($user->hasRole('doctor')) {
                return redirect()->route('doctor.dashboard.index');
            }
            if ($user->hasRole('admin')) {
                return redirect()->route('admin.dashboard.index');
            }
            Auth::logout();

            return redirect()->route('login')->with([
                'flash_status' => 'error',
                'flash_message' => 'You are Unauthorized for this login.'
            ]);


        }
    } else {
        return view('auth.login');
    }

})->name('index');
//

// Home Page Routes
//Route::get('/', 'FrontendController@index')->name('index');
Route::get('/new-appointment/{doctorId}/{date}', 'FrontendController@show')->name('create.appointment');
Route::post('/book/appointment', 'FrontendController@store')->name('book.appointment');

Auth::routes(['verify' => true]);
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('social/{provide}', 'Auth\LoginController@redirectToProvider')->name('sociallogin');
Route::get('social/{provide}/callback', 'Auth\LoginController@handleProviderCallback')->name('socialCallBack');


Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/eyes', 'Backend\EyesController');
        Route::resource('/areacodes', 'Backend\AreaCodeController');
        Route::resource('/locations', 'Backend\LocationController');
        Route::resource('/users', 'Backend\UserController');
    });
    //Doctor Routes
    Route::prefix('doctor')->name('doctor.')->group(function () {
        Route::get('/dashboard', 'Doctor\MainController@index')->name('dashboard.index');
        Route::get('/get/patient/data', 'Doctor\PatientController@getPatientData')->name('patient.ajax.data');
        Route::resource('/patient', 'Doctor\PatientController');
        Route::post('/patient/import/file', 'Doctor\PatientController@importFile')->name('patient.import.excel');

        Route::post('send/email', 'Doctor\PatientController@sendEmail')->name('send.email');
        Route::post('/patient/bulk/delete', 'Doctor\PatientController@bulkDelete')->name('patient.bulk.delete');

        Route::get('/print/recall/letterhead/one/{patient_id}', 'Doctor\PatientController@printDocumentOne')->name('patient.print.recall.letterhead.one');
        Route::get('/print/recall/letterhead/two/{patient_id}', 'Doctor\PatientController@printDocumentTwo')->name('patient.print.recall.letterhead.two');

        Route::get('/fellow/patients', 'Doctor\PatientController@fetchPatientData')->name('fellow.patient.index');
        Route::get('/fetch/patients', 'Doctor\PatientController@fetchFetchData')->name('fellow.patient.ajax.data');
        Route::get('/fetch/patients/{id}/edit', 'Doctor\PatientController@FellowEdit')->name('fellow.patient.edit');
        Route::post('/fetch/patients/{id}/update', 'Doctor\PatientController@FellowUpdate')->name('fellow.patient.update');

        Route::resource('appointment', 'Doctor\AppointmentController');
        Route::post('/appointment/check', 'Doctor\AppointmentController@check')->name('appointment.check');
        Route::post('/appointment/update', 'Doctor\AppointmentController@updateTime')->name('appointment.check.update');

        Route::get('/bookings', 'Doctor\BookingController@index')->name('bookings.index');
        Route::get('/bookings/status/update/{id}', 'Doctor\BookingController@toggleStatus')->name('bookings.update.status');

        // Labeling Patients
        Route::get('/labeling/patients', 'Doctor\PatientController@fetchLabelingPatientData')->name('labeling.patient.index');
        Route::get('/labeling/fetch/patients', 'Doctor\PatientController@fetchLabelingFetchData')->name('labeling.patient.ajax.data');

    });

    Route::prefix('ajax')->name('ajax.')->group(function () {
        Route::post('/notification/is-read', 'AjaxController@isRead')->name('notification.is-read');

    });
});

app/Http/Controllers/Doctor/AppointmentController.php
<?php

namespace App\Http\Controllers\Doctor;
use App\Http\Controllers\Controller;
use App\Models\Location;
use Illuminate\Http\Request;
use App\Models\Appointment;
use App\Models\Time;


class AppointmentController extends Controller
{

    public function __construct()
    {
        $this->middleware('role:doctor');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $myAppointments = Appointment::latest()->where('doctor_id', auth()->user()->id)->get();
        return view('doctor.appointment.index', compact('myAppointments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $locations = Location::all();
        return view('doctor.appointment.create', compact('locations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validation, unique:table,column with the column id == user_id
        $this->validate($request, [
//            'date' => 'required|unique:appointments,location,NULL,id,doctor_id,' . \Auth::id(),
            'date' => 'required',
            'location' => 'required',
            'time' => 'required'
        ]);

        $appointment = Appointment::create([
            'doctor_id' => auth()->user()->id,
            'date' => $request->date,
            'location' => $request->location,
        ]);
        foreach ($request->time as $time) {
            Time::create([
                'appointment_id' => $appointment->id,
                'time' => $time
                // default status => 0
            ]);
        }
        return redirect()->back()->with([
            'flash_status' => 'success',
            'flash_message' => 'An appointment created for ' . $request->date
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    // Check specific date for appointment time
    public function check(Request $request)
    {
        $date = $request->date;
        $appointment = Appointment::where('date', $date)->where('doctor_id', auth()->user()->id)->first();
        if (!$appointment) {
            return redirect()->to('/doctor/appointment')
                ->with([
                    'flash_status' => 'error',
                    'flash_message' => 'Appointment time is not available for this date'
                ]);
        };
        $appointmentId = $appointment->id;
        $times = Time::where('appointment_id', $appointmentId)->get();
        return view('doctor.appointment.index', compact('times', 'appointmentId', 'date'));
    }
    // Update app time
    // delete the old time array and create a new time array
    public function updateTime(Request $request)
    {
        $appointmentId = $request->appointmentId;
        $date = Appointment::where('id', $appointmentId)->get('date')->first()->date;
        Time::where('appointment_id', $appointmentId)->delete();
        foreach ($request->time as $time) {
            Time::create([
                'appointment_id' => $appointmentId,
                'time' => $time,
                'status' => 0
            ]);
        }
        return redirect()->route('doctor.appointment.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Appointment time for ' . $date . ' is updated successfully!'
            ]);
    }
}

app/Http/Controllers/Doctor/BookingController.php
<?php

namespace App\Http\Controllers\Doctor;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Models\Booking;

class BookingController extends Controller
{
    public function index(Request $request)
    {
        // Set timezone
//        date_default_timezone_set('America/New_York');
        if ($request->date) {
            $date = $request->date;
            $bookings = Booking::latest()->where('date', $date)->get();
            return view('doctor.bookings.index', compact('bookings', 'date'));
        }
        $bookings = Booking::latest()->where('date', date('Y-m-d'))->get();
        return view('doctor.bookings.index', compact('bookings'));
    }

    public function toggleStatus($id)
    {
        $booking = Booking::find($id);
        $booking->status = !$booking->status;
        $booking->save();
        return redirect()->back();
    }
}

app/Http/Controllers/Doctor/MainController.php
<?php

namespace App\Http\Controllers\Doctor;

use App\Http\Controllers\Controller;
use App\Models\Booking;
use App\Models\Patient;
use Illuminate\Support\Facades\Auth;


class MainController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:doctor');
    }

    public function index()
    {
        $patients = Patient::where('user_id', Auth::id())->count();
        $confirmed_booking = Booking::where('doctor_id', Auth::id())->whereStatus(0)->count();
        $pending_booking = Booking::where('doctor_id', Auth::id())->whereStatus(1)->count();
        return view('doctor.dashboard.index', compact('patients', 'confirmed_booking', 'pending_booking'));
    }

}

resources/views/doctor/labeling-patient/index.blade.php
@extends('doctor.main')
@section('title','Dashboard')
@push('css')
    <link href="{{ asset('/') }}admin_assets/global/plugins/datatables/datatables.min.css" rel="stylesheet"
          type="text/css"/>

    <link href="{{ asset('/') }}admin_assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css"
          rel="stylesheet" type="text/css"/>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet"
          type="text/css"/>
    <style type="text/css">
        .table td, .table th {
            font-size: 12px;
            line-height: 2.42857 !important;
        }
    </style>

@endpush
@section('banner')
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="{{ route('doctor.dashboard.index') }}"><i
                                            class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="{{ route('doctor.patient.index') }}">Labeling Patient</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">List</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="row">

        <div class="col-md-12" style="margin-top:100px;">
            <div class="form-group row">
                <div class="col-md-12">
                    <h4>Filter</h4>
                </div>
                <div class="col-md-12">
                    <div class="form-group row">
                        <div class="col-md-3">

                            <label for="year"
                                   class="col-md-4 col-form-label text-md-left"><strong>Year</strong></label>
                            <select
                                class="form-control @error('year') is-invalid @enderror" id="year" required
                                name="year" autocomplete="year">

                                <option value="">Select an option</option>
                                @for($i=1990;$i<=2050;$i++)
                                    <option value="{{$i}}">{{ $i }}</option>
                                @endfor
                            </select>
                        </div>
                        <div class="col-md-3">

                            <label for="month"
                                   class="col-md-4 col-form-label text-md-left"><strong>Month</strong></label>

                            <select
                                class="form-control @error('month') is-invalid @enderror" id="month" required
                                name="month" autocomplete="month">

                                <option value="">Select an option</option>
                                @for($i=1;$i<=12;$i++)
                                    <option value="{{$i}}">{{ $i }}</option>
                                @endfor
                            </select>
                        </div>
                        <div class="col-md-3">

                            <label for="day"
                                   class="col-md-4 col-form-label text-md-left"><strong>Day</strong></label>

                            <select
                                class="form-control @error('day') is-invalid @enderror" id="day" required
                                name="day" autocomplete="day">

                                <option value="">Select an option</option>
                                @for($i=1;$i<=31;$i++)
                                    <option value="{{$i}}">{{ $i }}</option>
                                @endfor
                            </select>
                        </div>
                        <div class="col-md-3">
                            <button type="button" class="btn btn-sm btn-success" id="searchPatient"
                                    style="margin-top: 47px;padding: 10px;font-size: 15px;margin-right: 15px">
                                Submit to View Patients
                            </button>
                        </div>
                    </div>
                </div>

            </div>

        </div>
        <div class="col-md-12">
            <div class="col">
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header border-0">
                        <h3 class="mb-0">Labeling Patient Record</h3>
                    </div>
                    <!-- Light table -->
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush" id="user_datatable_ajax">
                            <thead class="thead-light">
                            <tr>
                                <th>Doctor Name</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Address</th>
                                <th>Postal Code</th>
                            </tr>
                            </thead>
                            <tbody class="list">
                            </tbody>
                        </table>

                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('/') }}admin_assets/global/scripts/datatable.js" type="text/javascript"></script>

    <script src="{{ asset('/') }}admin_assets/global/plugins/datatables/datatables.min.js"
            type="text/javascript"></script>

    <script src="{{ asset('/') }}admin_assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"
            type="text/javascript"></script>
    <script src="{{asset('datatables/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('datatables/buttons.print.min.js')}}"></script>
    <script src="{{asset('datatables/buttons.html5.min.js')}}"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script>

        $(function () {

            var oTable = '';
            $('#searchPatient').on('click', function (e) {
                if ($('#day').find(":selected").val() == '' && $('#month').find(":selected").val() == '' && $('#year').find(":selected").val() == '') {
                    alert('Please select at least one option to filter patients record');
                } else {
                    oTable = $('#user_datatable_ajax').DataTable({
                        processing: true,
                        serverSide: true,
                        stateSave: true,
                        // searching: true,
                        "pagingType": "simple",
                        retrieve: true,
                        dom: 'Bfrtip',
                        "pageLength": 20000,
                        "order": [[0, "asc"]],
                        "buttons": [
                            {
                                extend: 'excelHtml5',
                                title: "Labeling Patient",
                                filename: "Labeling Patient",
                                "createEmptyCells": true,
                                sheetName: "Labeling Patient",
                                text: "Export to xlsx",
                                action:newExportAction

                            }


                        ],
                        ajax: {
                            url: '{!! route('doctor.labeling.patient.ajax.data') !!}',
                            data: function (d) {
                                d.day = $('#day').find(":selected").val();
                                d.month = $('#month').find(":selected").val();
                                d.year = $('#year').find(":selected").val();
                            }
                        }, columns: [
                            {data: 'doctor_name', name: 'doctor_name'},
                            {data: 'first_name', name: 'first_name'},
                            {data: 'last_name', name: 'last_name'},
                            {data: 'address', name: 'address'},
                            {data: 'postal_code', name: 'postal_code'},

                        ]
                    });
                    oTable.draw();
                    e.preventDefault();
                }

            });

            var oldExportAction = function (self, e, dt, button, config) {
                if (button[0].className.indexOf('buttons-excel') >= 0) {
                    if ($.fn.dataTable.ext.buttons.excelHtml5.available(dt, config)) {
                        $.fn.dataTable.ext.buttons.excelHtml5.action.call(self, e, dt, button, config);
                    }
                    else {
                        $.fn.dataTable.ext.buttons.excelFlash.action.call(self, e, dt, button, config);
                    }
                } else if (button[0].className.indexOf('buttons-print') >= 0) {
                    $.fn.dataTable.ext.buttons.print.action(e, dt, button, config);
                }
            };

            var newExportAction = function (e, dt, button, config) {
                var self = this;
                var oldStart = dt.settings()[0]._iDisplayStart;

                dt.one('preXhr', function (e, s, data) {
                    // Just this once, load all data from the server...
                    data.start = 0;
                    data.length = 2147483647;

                    dt.one('preDraw', function (e, settings) {
                        // Call the original action function
                        oldExportAction(self, e, dt, button, config);

                        dt.one('preXhr', function (e, s, data) {
                            // DataTables thinks the first item displayed is index 0, but we're not drawing that.
                            // Set the property to what it was before exporting.
                            settings._iDisplayStart = oldStart;
                            data.start = oldStart;
                        });

                        // Reload the grid with the original page. Otherwise, API functions like table.cell(this) don't work properly.
                        setTimeout(dt.ajax.reload, 0);

                        // Prevent rendering of the full data to the DOM
                        return false;
                    });
                });

                // Requery the server with the new one-time export settings
                dt.ajax.reload();
            };


        });
    </script>


@endpush