routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check()) {
        $user = Auth::user();
        if ($user->status == 'suspended') {
            Auth::logout();
            return redirect()->route('index')->with([
                'flash_status' => 'error',
                'flash_message' => 'Your Account has been suspended.Please Contact Support.'
            ]);
        } else {

            if ($user->hasRole('doctor')) {
                return redirect()->route('doctor.dashboard.index');
            }
            if ($user->hasRole('admin')) {
                return redirect()->route('admin.dashboard.index');
            }
            Auth::logout();

            return redirect()->route('login')->with([
                'flash_status' => 'error',
                'flash_message' => 'You are Unauthorized for this login.'
            ]);


        }
    } else {
        return view('auth.login');
    }

})->name('index');
//

// Home Page Routes
//Route::get('/', 'FrontendController@index')->name('index');
Route::get('/new-appointment/{doctorId}/{date}', 'FrontendController@show')->name('create.appointment');
Route::post('/book/appointment', 'FrontendController@store')->name('book.appointment');

Auth::routes(['verify' => true]);
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('social/{provide}', 'Auth\LoginController@redirectToProvider')->name('sociallogin');
Route::get('social/{provide}/callback', 'Auth\LoginController@handleProviderCallback')->name('socialCallBack');


Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/eyes', 'Backend\EyesController');
        Route::resource('/areacodes', 'Backend\AreaCodeController');
        Route::resource('/locations', 'Backend\LocationController');
        Route::resource('/users', 'Backend\UserController');
    });
    //Doctor Routes
    Route::prefix('doctor')->name('doctor.')->group(function () {
        Route::get('/dashboard', 'Doctor\MainController@index')->name('dashboard.index');
        Route::get('/get/patient/data', 'Doctor\PatientController@getPatientData')->name('patient.ajax.data');
        Route::resource('/patient', 'Doctor\PatientController');
        Route::post('/patient/import/file', 'Doctor\PatientController@importFile')->name('patient.import.excel');

        Route::post('send/email', 'Doctor\PatientController@sendEmail')->name('send.email');
        Route::post('/patient/bulk/delete', 'Doctor\PatientController@bulkDelete')->name('patient.bulk.delete');

        Route::get('/print/recall/letterhead/one/{patient_id}', 'Doctor\PatientController@printDocumentOne')->name('patient.print.recall.letterhead.one');
        Route::get('/print/recall/letterhead/two/{patient_id}', 'Doctor\PatientController@printDocumentTwo')->name('patient.print.recall.letterhead.two');

        Route::get('/fellow/patients', 'Doctor\PatientController@fetchPatientData')->name('fellow.patient.index');
        Route::get('/fetch/patients', 'Doctor\PatientController@fetchFetchData')->name('fellow.patient.ajax.data');
        Route::get('/fetch/patients/{id}/edit', 'Doctor\PatientController@FellowEdit')->name('fellow.patient.edit');
        Route::post('/fetch/patients/{id}/update', 'Doctor\PatientController@FellowUpdate')->name('fellow.patient.update');

        Route::resource('appointment', 'Doctor\AppointmentController');
        Route::post('/appointment/check', 'Doctor\AppointmentController@check')->name('appointment.check');
        Route::post('/appointment/update', 'Doctor\AppointmentController@updateTime')->name('appointment.check.update');

        Route::get('/bookings', 'Doctor\BookingController@index')->name('bookings.index');
        Route::get('/bookings/status/update/{id}', 'Doctor\BookingController@toggleStatus')->name('bookings.update.status');

        // Labeling Patients
        Route::get('/labeling/patients', 'Doctor\PatientController@fetchLabelingPatientData')->name('labeling.patient.index');
        Route::get('/labeling/fetch/patients', 'Doctor\PatientController@fetchLabelingFetchData')->name('labeling.patient.ajax.data');

    });

    Route::prefix('ajax')->name('ajax.')->group(function () {
        Route::post('/notification/is-read', 'AjaxController@isRead')->name('notification.is-read');

    });
});

app/Models/AreaCode.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AreaCode extends Model
{
    protected $table = 'area_codes';
    protected $guarded = [];
}

app/Http/Controllers/Backend/AjaxController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;


use App\Traits\GeneralHelperTrait;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Validator;



class AjaxController extends Controller
{
    use GeneralHelperTrait;

    public function example(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
        ], [

        ]);

        if (!$validator->fails()) {


            $response['status'] = 'success';
            $response['data'] = [

            ];
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;
    }



}

app/Http/Controllers/Backend/AreaCodeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\AreaCode;
use Illuminate\Http\Request;

class AreaCodeController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $areacodes = AreaCode::orderBy('id', 'DESC')->get();

        return view('backend.areacodes.index', compact('areacodes'));
    }

    public function create()
    {
        return view('backend.areacodes.create');

    }

    public function store(Request $request)
    {
        $areacode = new AreaCode();
        $areacode->code = $request->code ?? 'null';
        $areacode->save();
        return redirect()->route('admin.areacodes.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Area Code created successfully.'
            ]);

    }

    public function edit($id)
    {
        $areacode = AreaCode::find($id);
        return view('backend.areacodes.edit', compact('areacode'));
    }

    public function update(Request $request, $id)
    {
        $areacode = AreaCode::find($id);
        $areacode->code = $request->code ?? 'null';
        $areacode->save();

        return redirect()->route('admin.areacode.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Area Code updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $areacode = AreaCode::findOrFail($id);
        $areacode->delete();

        return redirect()->route('admin.areacode.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Area Code has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;


class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $doctors = User::where('user_type', 'doctor')->get();
        return view('backend.dashboard.index',compact('doctors'));
    }
}

app/Http/Controllers/Backend/EyesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

use App\Models\Eye;
use Illuminate\Http\Request;

class EyesController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $eyes = Eye::orderBy('id', 'DESC')->get();

        return view('backend.eyes.index', compact('eyes'));
    }

    public function create()
    {
        return view('backend.eyes.create');

    }

    public function store(Request $request)
    {
        $eye = new Eye();
        $eye->rx_r      = $request->rx_r ?? 'null';
        $eye->rx_r_one  = $request->rx_r_one;
        $eye->rx_r_two  = $request->rx_r_two;
        $eye->rx_l      = $request->rx_l ?? 'null';
        $eye->rx_l_one  = $request->rx_l_one;
        $eye->rx_l_two  = $request->rx_l_two;
        $eye->add       = $request->add ?? 'null';
        $eye->save();
        return redirect()->route('admin.eyes.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Eye created successfully.'
            ]);

    }

    public function edit($id)
    {
        $eye = Eye::find($id);
        return view('backend.eyes.edit', compact('eye'));
    }

    public function update(Request $request, $id)
    {
        $eye= Eye::find($id);
        $eye->rx_r      = $request->rx_r ?? 'null';
        $eye->rx_r_one  = $request->rx_r_one;
        $eye->rx_r_two  = $request->rx_r_two;
        $eye->rx_l      = $request->rx_l ?? 'null';
        $eye->rx_l_one  = $request->rx_l_one;
        $eye->rx_l_two  = $request->rx_l_two;
        $eye->add       = $request->add ?? 'null';
        $eye->save();

        return redirect()->route('admin.eyes.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Eye updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $eye = Eye::findOrFail($id);
        $eye->delete();

        return redirect()->route('admin.eyes.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Eye has been deleted'
            ]);
    }

}

app/Http/Controllers/Backend/LocationController.php
<?php
namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Location;
use Illuminate\Http\Request;


class LocationController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $locations = Location::orderBy('id', 'DESC')->get();

        return view('backend.locations.index', compact('locations'));
    }

    public function create()
    {
        return view('backend.locations.create');

    }

    public function store(Request $request)
    {
        $location = new Location();
        $location->location = $request->location ?? 'null';
        $location->save();
        return redirect()->route('admin.locations.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Location created successfully.'
            ]);

    }

    public function edit($id)
    {
        $location = Location::find($id);
        return view('backend.locations.edit', compact('location'));
    }

    public function update(Request $request, $id)
    {
        $location = Location::find($id);
        $location->location = $request->location ?? 'null';
        $location->save();

        return redirect()->route('admin.location.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Location updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $location = Location::findOrFail($id);
        $location->delete();

        return redirect()->route('admin.location.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Location has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

use App\Models\Role;
use App\Models\User;
use App\Models\UserRole;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;


class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $users = User::orderBy('id', 'DESC')->where('user_type', 'doctor')->get();
        return view('backend.users.index', compact('users'));
    }

    public function create()
    {
        return view('backend.users.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required|string',
            'last_name' => 'required|string',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
            'password_confirmation' => 'required|same:password',
            'image' => 'required|image|mimes:jpg,jpeg,png|max:2048',

        ], [
            'first_name.required' => 'First name is required.',
            'last_name.required' => 'Last name is required.',
            'email.required' => 'Email is required.',
        ]);


        $role = Role::find(2);

        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/signature');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $e_signature = $name;
        } else {

            $e_signature = 'default.png';
        }
        $user = User::create([
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'role_id' => $role->id,
            'user_type' => $role->name,
            'status' => 'verified',
            'email' => $request->get('email'),
            'password' => Hash::make($request->get('password')),
            'e_signature'=>$e_signature
        ]);

        UserRole::create([
            'user_id' => $user->id,
            'role_id' => $role->id
        ]);

        return redirect()->route('admin.users.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'User created successfully.'
            ]);
    }

    public function edit($id)
    {
        $user = User::find($id);

        return view('backend.users.edit', compact('user'));


    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'first_name' => 'required|string',
            'last_name' => 'required|string',
            'email' => 'required|string|email|max:255',
            'image' => 'image|mimes:jpg,jpeg,png|max:2048',
        ], [
            'first_name.required' => 'First name is required.',
            'last_name.required' => 'Last name is required.',
            'email.required' => 'Email is required.',

        ]);

        $user = User::find($id);


        $role = Role::find(2);


        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/signature');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $e_signature = $name;
        } else {
            $e_signature = $user->e_signature;
        }
        $user->update([
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'role_id' => $role->id,
            'user_type' => $role->name,
            'status' => 'verified',
            'email' => $request->get('email'),
            'password' => Hash::make($request->get('password')),
            'e_signature' => $e_signature,
        ]);
        (new \App\Models\UserRole)->update([
            'user_id' => $user->id,
            'role_id' => $role->id
        ]);

        return redirect()->route('admin.users.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'User updated successfully.'
            ]);
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('admin.users.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'User has been deleted'
            ]);
    }

}

resources/views/backend/areacodes/create.blade.php
@extends('layouts.master')
@section('title','Area Codes')
@push('css')
    <style>
        .invalid-feedback {
            font-size: 80%;
            display: block;
            width: 100%;
            margin-top: .25rem;
            color: #fb6340;
        }
    </style>
@endpush
@section('banner')
    <div class="header pb-6 d-flex align-items-center"><!-- Mask -->
        <span class="mask bg-gradient-default opacity-8"></span>
    </div>
@endsection
@section('content')
    <div class="row" style="margin-top: 10px">
        <div class="col-xl-12 order-xl-1">
            <div class="card">

                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Create Area Code </h3>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('admin.areacodes.store') }}" autocomplete="off">
                        @csrf
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group  @error('code') is-invalid @enderror">
                                        <label class="form-control-label" for="code">Area Code</label>
                                        <input type="text" id="code" value="{{ old('code') }}" class="form-control" name="code"
                                               placeholder="Area Code">
                                        @error('code')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pl-lg-4">
                            <div class="row align-items-center">
                                <div class="col-4 text-right">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
@endsection
@push('js')



@endpush

resources/views/backend/areacodes/edit.blade.php
@extends('layouts.master')
@section('title','Edit Area Code')
@push('css')
    <style>
        .invalid-feedback {
            font-size: 80%;
            display: block;
            width: 100%;
            margin-top: .25rem;
            color: #fb6340;
        }
    </style>
@endpush
@section('banner')
    <div class="header pb-6 d-flex align-items-center"><!-- Mask -->
        <span class="mask bg-gradient-default opacity-8"></span>

    </div>
@endsection
@section('content')
    <div class="row" style="margin-top: 10px">
        <div class="col-xl-12 order-xl-1">
            <div class="card">

                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('admin.areacodes.update',$areacode->id) }}" autocomplete="off">
                        @method('patch')
                        @csrf
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group  @error('code') is-invalid @enderror">
                                        <label class="form-control-label" for="code">Area Code</label>
                                        <input type="text" id="code" value="{{ old('code',$areacode->code) }}" class="form-control" name="code"
                                               placeholder="Area Code">
                                        @error('code')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="pl-lg-4">
                            <div class="row align-items-center">
                                <div class="col-4 text-right">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
@endsection
@push('js')



@endpush

resources/views/backend/areacodes/index.blade.php
@extends('layouts.master')
@section('title','Area Codes')
@push('css')
    <link rel="stylesheet" type="text/css"
          href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">

@endpush
@section('banner')
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Area Codes</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard.index') }}"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="{{ route('admin.areacodes.index') }}">Area Codes</a></li>
                                <li class="breadcrumb-item active" aria-current="page">List</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        <a href="{{ route('admin.areacodes.create') }}" class="btn btn-sm btn-success" style="padding: 13px;font-size: 15px;margin-right: 15px">Create</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="row">

        <div class="col-md-12">
            <div class="col">
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header border-0">
                        <h3 class="mb-0">Area Code Record</h3>
                    </div>
                    <!-- Light table -->
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush" id="example">
                            <thead class="thead-light">
                            <tr>
                                <th>Action</th>
                                <th>Code</th>
                            </tr>
                            </thead>
                            <tbody class="list">
                            @if(!empty($areacodes) && count($areacodes) >0)
                                @foreach($areacodes as $areacode)
                                    <tr>
                                        <td nowrap style="width: 12%;">
                                            <a href="{{route('admin.areacodes.edit',$areacode->id)}}" style="margin: 10px;"
                                               class="btn btn-sm btn-info pull-left ">Edit</a>
                                            <form method="post" action="{{ route('admin.areacodes.destroy', $areacode->id) }}"
                                                  id="delete_{{ $areacode->id }}">
                                                @csrf
                                                @method('DELETE')
                                                <a style="margin-left:10px;" class="btn btn-sm btn-danger m-left"
                                                   href="javascript:void(0)"
                                                   onclick="if(confirmDelete()){ document.getElementById('delete_<?=$areacode->id?>').submit(); }">
                                                    Delete
                                                </a>
                                            </form>
                                        </td>
                                        <td>{{ $areacode->code ?? ''}}</td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script type="text/javascript" charset="utf8"
            src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
    <script>
        $(function () {
            $("#example").dataTable();
        })
    </script>


@endpush