routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check()) {
        $user = Auth::user();
        if ($user->status == 'suspended') {
            Auth::logout();
            return redirect()->route('index')->with([
                'flash_status' => 'error',
                'flash_message' => 'Your Account has been suspended.Please Contact Support.'
            ]);
        } else {

            if ($user->hasRole('doctor')) {
                return redirect()->route('doctor.dashboard.index');
            }
            if ($user->hasRole('admin')) {
                return redirect()->route('admin.dashboard.index');
            }
            Auth::logout();

            return redirect()->route('login')->with([
                'flash_status' => 'error',
                'flash_message' => 'You are Unauthorized for this login.'
            ]);


        }
    } else {
        return view('auth.login');
    }

})->name('index');
//

// Home Page Routes
//Route::get('/', 'FrontendController@index')->name('index');
Route::get('/new-appointment/{doctorId}/{date}', 'FrontendController@show')->name('create.appointment');
Route::post('/book/appointment', 'FrontendController@store')->name('book.appointment');

Auth::routes(['verify' => true]);
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('social/{provide}', 'Auth\LoginController@redirectToProvider')->name('sociallogin');
Route::get('social/{provide}/callback', 'Auth\LoginController@handleProviderCallback')->name('socialCallBack');


Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/eyes', 'Backend\EyesController');
        Route::resource('/areacodes', 'Backend\AreaCodeController');
        Route::resource('/locations', 'Backend\LocationController');
        Route::resource('/users', 'Backend\UserController');
    });
    //Doctor Routes
    Route::prefix('doctor')->name('doctor.')->group(function () {
        Route::get('/dashboard', 'Doctor\MainController@index')->name('dashboard.index');
        Route::get('/get/patient/data', 'Doctor\PatientController@getPatientData')->name('patient.ajax.data');
        Route::resource('/patient', 'Doctor\PatientController');
        Route::post('/patient/import/file', 'Doctor\PatientController@importFile')->name('patient.import.excel');

        Route::post('send/email', 'Doctor\PatientController@sendEmail')->name('send.email');
        Route::post('/patient/bulk/delete', 'Doctor\PatientController@bulkDelete')->name('patient.bulk.delete');

        Route::get('/print/recall/letterhead/one/{patient_id}', 'Doctor\PatientController@printDocumentOne')->name('patient.print.recall.letterhead.one');
        Route::get('/print/recall/letterhead/two/{patient_id}', 'Doctor\PatientController@printDocumentTwo')->name('patient.print.recall.letterhead.two');

        Route::get('/fellow/patients', 'Doctor\PatientController@fetchPatientData')->name('fellow.patient.index');
        Route::get('/fetch/patients', 'Doctor\PatientController@fetchFetchData')->name('fellow.patient.ajax.data');
        Route::get('/fetch/patients/{id}/edit', 'Doctor\PatientController@FellowEdit')->name('fellow.patient.edit');
        Route::post('/fetch/patients/{id}/update', 'Doctor\PatientController@FellowUpdate')->name('fellow.patient.update');

        Route::resource('appointment', 'Doctor\AppointmentController');
        Route::post('/appointment/check', 'Doctor\AppointmentController@check')->name('appointment.check');
        Route::post('/appointment/update', 'Doctor\AppointmentController@updateTime')->name('appointment.check.update');

        Route::get('/bookings', 'Doctor\BookingController@index')->name('bookings.index');
        Route::get('/bookings/status/update/{id}', 'Doctor\BookingController@toggleStatus')->name('bookings.update.status');

        // Labeling Patients
        Route::get('/labeling/patients', 'Doctor\PatientController@fetchLabelingPatientData')->name('labeling.patient.index');
        Route::get('/labeling/fetch/patients', 'Doctor\PatientController@fetchLabelingFetchData')->name('labeling.patient.ajax.data');

    });

    Route::prefix('ajax')->name('ajax.')->group(function () {
        Route::post('/notification/is-read', 'AjaxController@isRead')->name('notification.is-read');

    });
});

resources/views/includes/footer.blade.php
<footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-6">
            <div class="copyright text-center  text-lg-left  text-muted">
                &copy; 2020 <a href="#" class="font-weight-bold ml-1"
                               target="_blank">Medical</a>
            </div>
        </div>
    </div>
</footer>

resources/views/includes/header.blade.php
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center  ml-md-auto ">
                <li class="nav-item d-xl-none">
                    <!-- Sidenav toggler -->
                    <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin"
                         data-target="#sidenav-main">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </div>
                </li>
                <li class="nav-item d-sm-none">
                    <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                        <i class="ni ni-zoom-split-in"></i>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        <div class="media align-items-center">
                  <span class="avatar avatar-sm rounded-circle">
                  </span>
                            <div class="media-body  ml-2  d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold"> {{ auth()->user()->fullName() }}</span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu  dropdown-menu-right ">
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>
                        <div class="dropdown-divider"></div>

                        <a href="javascript:void(0);"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                           class="dropdown-item"><i class="ni ni-user-run"></i> <span>Logout</span></a>
                        <form id="logout-form" action="{{ route('logout') }}"
                              enctype="multipart/form-data"
                              method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/includes/sidebar.blade.php
<!-- Sidenav -->
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
        <!-- Brand -->
        <div class="sidenav-header  align-items-center">
            <a class="navbar-brand" href="javascript:void(0)">
                <p>Medical</p>
            </a>
        </div>
        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Nav items -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('admin/dashboard')) ? 'active' : '' }}"
                           href="{{ route('admin.dashboard.index') }}">
                            <i class="ni ni-tv-2 text-primary"></i>
                            <span class="nav-link-text">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('admin/eyes')) ? 'active' : '' }}"
                           href="{{ route('admin.eyes.index') }}">
                            <i class="ni ni-tv-2 text-primary"></i>
                            <span class="nav-link-text">Eye</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('admin/areacodes')) ? 'active' : '' }}"
                           href="{{ route('admin.areacodes.index') }}">
                            <i class="ni ni-tv-2 text-primary"></i>
                            <span class="nav-link-text">Area Codes</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('admin/locations')) ? 'active' : '' }}"
                           href="{{ route('admin.locations.index') }}">
                            <i class="ni ni-tv-2 text-primary"></i>
                            <span class="nav-link-text">Locations</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('admin/users')) ? 'active' : '' }}"
                           href="{{ route('admin.users.index') }}">
                            <i class="ni ni-single-02 text-primary"></i>
                            <span class="nav-link-text">Users</span>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</nav>